# Generated by Django 6.0.5 on 2026-05-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nom', models.CharField(max_length=100)),
                ('immatriculation', models.CharField(max_length=50, unique=True)),
                ('type_moto', models.CharField(choices=[('taxi', 'Moto Taxi'), ('ordures', 'Ramassage Ordures')], default='taxi', max_length=20)),
                ('montant_journalier', models.DecimalField(decimal_places=0, default=8000, max_digits=10)),
                ('etat', models.CharField(choices=[('active', 'Active'), ('panne', 'En panne'), ('maintenance', 'Maintenance'), ('repos', 'Repos')], default='active', max_length=20)),
                ('date_achat', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='motos/')),
                ('observations', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Moto',
                'ordering': ['nom'],
            },
        ),
    ]
