# Generated by Django 6.0.5 on 2026-05-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Paiement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('montant_attendu', models.DecimalField(decimal_places=0, max_digits=10)),
                ('montant_verse', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('paye', 'Payé'), ('partiel', 'Partiel'), ('absent', 'Absent'), ('panne', 'En panne')], default='paye', max_length=20)),
                ('observations', models.TextField(blank=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paiements', to='motos.moto')),
            ],
            options={
                'verbose_name': 'Paiement',
                'ordering': ['-date'],
                'unique_together': {('moto', 'date')},
            },
        ),
    ]
