# Generated by Django 6.0.5 on 2026-05-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaintenancePreventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('type_maintenance', models.CharField(choices=[('vidange', 'Vidange'), ('pneus', 'Pneus'), ('freins', 'Freins'), ('moteur', 'Révision moteur'), ('assurance', 'Assurance'), ('visite', 'Visite technique'), ('autre', 'Autre')], max_length=30)),
                ('date_prevue', models.DateField()),
                ('date_realisation', models.DateField(blank=True, null=True)),
                ('cout', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('statut', models.CharField(choices=[('planifie', 'Planifié'), ('fait', 'Fait'), ('urgent', 'Urgent'), ('en_retard', 'En retard')], default='planifie', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='motos.moto')),
            ],
            options={
                'verbose_name': 'Maintenance préventive',
                'ordering': ['date_prevue'],
            },
        ),
    ]
