# Generated by Django 6.0.5 on 2026-05-18 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('categorie', models.CharField(choices=[('carburant', 'Carburant'), ('reparation', 'Réparation'), ('assurance', 'Assurance'), ('administratif', 'Administratif'), ('personnel', 'Personnel'), ('autre', 'Autre')], max_length=30)),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Epargne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('montant', models.DecimalField(decimal_places=0, max_digits=10)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Épargne',
                'ordering': ['-date'],
            },
        ),
    ]
