# Generated by Django 6.0.5 on 2026-05-18 21:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('motos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Panne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date_panne', models.DateField()),
                ('date_reparation', models.DateField(blank=True, null=True)),
                ('type_panne', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('cout_reparation', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('garagiste', models.CharField(blank=True, max_length=100)),
                ('statut', models.CharField(choices=[('en_cours', 'En cours'), ('reparee', 'Réparée'), ('abandonnee', 'Abandonnée')], default='en_cours', max_length=20)),
                ('facture', models.ImageField(blank=True, null=True, upload_to='pannes/')),
                ('observations', models.TextField(blank=True)),
                ('moto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pannes', to='motos.moto')),
            ],
            options={
                'verbose_name': 'Panne',
                'ordering': ['-date_panne'],
            },
        ),
    ]
